title: A data odyssey
description: A blog to qualquer coisa 
author: Renata Cabral
logo: /static/img/avatar.png
github: https://github.com/renatakc
about: Data Science aspirant

baseurl: ""
url: "https://renatakc.github.io/"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \renatakc
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
